### PR TITLE
Changelog for 2.3.0

### PR DESCRIPTION
**Pull request by acinader**
Draft changelog for 2.3.0

### CODE REVIEW

**Comment by flovilmart** [comment]
We usually do the changelog by hand, as it's more readable for humans and the commit history is already readable on github right?

**Comment by acinader** [comment]
I can certainly do that.  Will do as soon as I'm back in front of the keyboard in an hour or so.

**Comment by flovilmart** [comment]
I can take care of it too. There's an issue that I'd like to get in that release too: https://github.com/ParsePlatform/parse-server/issues/3195

STR are clear, the original test is there, that should be easy to fix :)

**Comment by acinader** [comment]
i'm putting together a draft that we can add to

**Comment by flovilmart** [comment]
Closing as supersed by #3205

**Pull request closed without merging**
