### PR TITLE
Update FilesController.js

### PR DESCRIPTION
**Pull request by mcclaskiem**
`config` was removed from calling createFile on adapter causing errors on save

### CODE REVIEW

**Comment by mcclaskiem** [comment]
Updated to 2.2.4 today via NPM and saving files was broken. Noticed this issue but wanted to confirm so re-opening

**Comment by flovilmart** [comment]
Which adapter is broken?

**Comment by mcclaskiem** [comment]
O gotcha I was using config for rack space and I saw S3 was using it as well in my node_modules but I can easily rewrite the rack space one to not use it.

**Comment by flovilmart** [comment]
https://github.com/parse-server-modules/parse-server-conformance-tests is the guideline for the files adapter, you can find plenty of examples across the https://github.com/parse-server-modules organization.

Sorry for the breaking change.

**Comment by flovilmart** [comment]
@mcclaskiem do you explicitly need the config or this was to match the API?

**Comment by mcclaskiem** [comment]
I was just trying to match the API at the time but I will go ahead and reconfigure my adapter. Thanks for the insight on updates!

**Pull request closed without merging**
