### PR TITLE
Implement pointer types in postgres.

### PR DESCRIPTION
**Pull request by drew-gross**
Store pointers as strings because in Parse you can create pointers to objects that don't exist (and even classes that don't exist)

Based on #2081, merge that first then update this branch on top of that.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by flovilmart** [comment]
Just merged, you still have conflicts, maybe because of the squash merge

**Comment by drew-gross** [comment]
Probably yea. Will rebase.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by flovilmart** [comment]
Waiting for travis but LGTM

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Pull request merged**
