### PR TITLE
Filter other users' email in all queries.

### PR DESCRIPTION
**Pull request by xissburg**
The email is sensitive information, thus it should be filtered in `filterSensitiveData` in `DatabaseController`.

### CODE REVIEW

**Comment by flovilmart** [comment]
@acinader isn't it already taken care of?

**Comment by xissburg** [comment]
Looks like I was using an older version without this update (email field is not returned anymore for Parse.User queries. (Provided only on the user itself if provided).

**Comment by MBDeveloper** [comment]
Can you remove the hardcoded adding of the mail to the sensitive data and let the developer add it in the config in case he want to, this change broke our administration clients that do need to get the user email. 
Is there a way to bypass this removing of the email for specific clients? I didn't find a way to do it.

**Comment by NatanRolnik** [comment]
@MBDeveloper you can see the suggestions here at #3301 by @acinader.

**Comment by MBDeveloper** [comment]
Writing a cloud function as suggested in  #3301 is not relevant to us since we are getting the user object from many other objects that have a pointer to the user object, this mean rewrite all our administration clients API calls.

**Comment by zingano** [comment]
Similar issue for me. I have an Admin role that on parse.com was totally able to follow links to user objects and access their email, and the same was true on old versions of parse server.

Looks like I'm stuck on old versions of parse server then.

**Pull request closed without merging**
