### PR TITLE
missing return in test.

### PR DESCRIPTION
**Pull request by jeacott1**

### CODE REVIEW

**Comment by jeacott1** [comment]
I'd also note that the query in this test (for me at least) never actually returns any results.

the same query is used in 'should support full RESTQuery for increment', and it too never returns any results. is something broken with RestQuery?

**Comment by flovilmart** [comment]
It never returns as the DB is empty, the test only test that it doesn't throw.

**Comment by jeacott1** [comment]
sure - but without the return, it doesn't fail even when PushQueue throws.

**Comment by jeacott1** [comment]
re the query - what I meant was that the query itself seems bogus as I don't think it could ever return any results even if there were data.

**Comment by flovilmart** [comment]
Given the blame info, this was added about a year ago, (https://github.com/ParsePlatform/parse-server/commit/b89619b6ee6a98b28a41d8e4df782974a2cda14a) when the Increment was failing when providing a REST query.

**Pull request merged**
