### PR TITLE
Adds ability to prevent login with unverified emails

### PR DESCRIPTION
**Pull request by cherukumilli**
Updated README file to show how to use the new config parameter (`allowLoginForUnverifiedEmail`) that was introduced in PR #2163 

```
var server = ParseServer({
  ...otherOptions,
  // Enable email verification
  verifyUserEmails: true,

  // allows user to login only after email verification
  allowLoginForUnverifiedEmail: false, // defaults to true

  // The public URL of your app.
  // This will appear in the link that is used to verify email addresses and reset passwords.
  // Set the mount path as it is in serverURL
  publicServerURL: 'https://example.com/parse',
...

```

### CODE REVIEW

**Comment by flovilmart** [comment]
Can you please do both PR as a single? That will help keeping track of everything.

**Comment by flovilmart** [comment]
Needs a Rebase and unit tests that cover that behavior before we can merge! Otherwise that look good.

**Comment by cherukumilli** [comment]
Closing this PR for now. I will open another one as soon as I get some time to squash the commits and add test cases.

**Comment by flovilmart** [comment]
Thanks ;) tests are important in order to maintain the feature over time.

**Pull request closed without merging**
