### PR TITLE
Support for nested `.select()` calls

### LINKED ISSUE #1567: select() constraint is not applied to included objects
I am running this same query from parse.com and on my local parse server . 

```
var messageQuery = new Parse.Query("Message");
    messageQuery.descending("updatedAt");
    messageQuery.include("channelId");
    messageQuery.select("channelId");
    messageQuery.select("channelId.exchange");
```
Channeld is pointer field to my other document.
On parse.com server this query works and return result with only exchange field and on parse-server it selects complete channelId document and prints everything.

### PR DESCRIPTION
**Pull request by flovilmart**
- Handle `keys` property in RestQuery when it contains nesting. 
- Support multiple level of nesting and inclusion

Fixes #1567

### CODE REVIEW

**Comment by flovilmart** [comment]
Fixes #2653 

Updated to use native field select in mongo and postgres

**Comment by facebook-github-bot-1** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2737/files/60cd3f1d77e3e08f8deb07dadeae824917a57e98..0f3e3af8a8a21d1d5ba632f3fb38f86f94ef8f6e)

**Comment by zenithanu** [comment]
Great job, I came up with the problem on Friday and this comes up on Monday, thanks for the work.

**Comment by flovilmart** [comment]
@zenithanu glad to help! Once reviewed and merged, this will be available by pointing your parse-server to `parseplatform/parse-server#latest`

**Comment by oazya500** [comment]
is there any way to  stop nested select future after update server . because all my queries will fail

and I will use this in future after update my apps 

thanks

**Comment by flovilmart** [comment]
@oazya500 what would fail in your app?

**Comment by oazya500** [comment]
ParseQuery<ParseObject> quere = ParseQuery.getQuery("MSGES");
    
        quere.selectKeys(["user", "CATOGREY"]);
        quere.include("CATOGREY");
        quere.include("userShare");
 
        quere.findInBackground(new FindCallback<ParseObject>() {
            @Override
            public void done(List<ParseObject> scoreList,
                             com.parse.ParseException e) {
          
                if (e != null) {
                   String name = parseObject.has("user") ?
                    parseObject.getParseObject("user").getString("name") : "U";
 String catname = parseObject.has("CATOGREY") ? parseObject.getParseObject("CATOGREY").getString("name") : "";
                } 

                }
            }
        });

    }

my old apps like above . so if I update server all my old apps will not git name for user or CATOGREY

and I should do like this in new app 
        quere.selectKeys(["user", "CATOGREY", "user.name", "CATOGREY.name"]);



and I want to updat server becuse I have this error in my server 

 ParseError { code: 101, message: 'Object not found.' }

and server restart after this error

app restart every 10 minute at most 

│ App name          │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem        │ watching │
├───────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼────────────┼─────────
│ msegate           │ 0  │ fork │ 5673 │ online │ 18      │ 2m     │ 0%  │ 133.0 MB   │ disabled │

**Comment by flovilmart** [comment]
The previous behavior is still valid with that PR. Because you call include(). The update you suggest would just return the name key of that object, and not the whole object.

**Comment by oazya500** [comment]
it Supposed to be  valid but Unfortunately not valid . give it try and you see it not valid even with include()

**Comment by oazya500** [comment]
did you mean for update I should do like this 

quere.selectKeys(["user", "CATOGREY", "user.name", "CATOGREY.name"]);
    quere.include("CATOGREY.name");
    quere.include("user.name");

**Comment by oazya500** [comment]
even with beforeFind not valid 

Parse.Cloud.beforeFind('MSGES', (req) => {
  let query = req.query;
    query.select("user","user.name","CATOGREY","CATOGREY.name");
return query;
or
  return Parse.Query.or(q, otherQuery);
});

**Comment by oazya500** [comment]
quere.selectKeys(["user", "CATOGREY", "user.name", "CATOGREY.name"]);
quere.include("CATOGREY");
quere.include("user");


that for future I was do that but parse-server not support it before 2.2.22

**Comment by oazya500** [comment]
any update how to stop nested select in new update

**Comment by flovilmart** [comment]
You can't disable that feature and it's unlikely to be removed as It was a bug compared to parse.com

**Comment by oazya500** [comment]
for other problem what I can do 

the problem is 

ParseError { code: 101, message: 'Object not found.' }

and server restart after this error

app restart every 10 minute at most

**Comment by flovilmart** [comment]
@oazya500 your server should not restart when logging an error. Are you using pm2 and monitoring the logs?

**Comment by oazya500** [comment]
@flovilmart  all off this app using parse server and one off them restart 260 times in tow day
Image of a1

**Comment by janswist** [comment]
`selectKeys` are no longer supported? I get this:
`Error generating response. TypeError: query.selectKeys is not a function
    at /app/cloud/main.js:13:8
    at /app/node_modules/parse-server/lib/Routers/FunctionsRouter.js:198:11
    at new Promise (<anonymous>)
    at handleCloudFunction (/app/node_modules/parse-server/lib/Routers/FunctionsRouter.js:166:16)
    at /app/node_modules/parse-server/lib/PromiseRouter.js:253:7
    at Layer.handle [as handle_request] (/app/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/parse-server/node_modules/express/lib/router/index.js:281:22`

**Pull request merged**
