### PR TITLE
Adding a test demonstrating issue #1840.

### PR DESCRIPTION
**Pull request by airdrummingfool**
This test demonstrates #1840: using `unset` to remove a child object leaves behind an `UnsetOp` in the child object's place when there is a non-trivial beforeSave on the parent object.

### CODE REVIEW

**Comment by flovilmart** [comment]
Awesome! Any clue for a fix proposal?

**Comment by airdrummingfool** [comment]
No ideas yet - if I get some time in the next couple of days I'll do some digging.

**Comment by airdrummingfool** [comment]
@flovilmart I found another bug that is related, but is exposed using `set('key', undefined)` instead of `unset('key')` and has a different outcome. Is it more appropriate to add it to this existing test, or write a new test?

**Comment by flovilmart** [comment]
Closing as we have a fix with Parse-JS 1.9

**Pull request closed without merging**
