### PR TITLE
Add npmignore

### PR DESCRIPTION
**Pull request by wangmengyan95**
For local dev, if we under `parse-sever-example` and run npm install, the compiled `lib` folder for `parse-sever` will not be moved to `parse-server-example/node_modules/parse-server`. This is because we have `lib` in gitignore. Adding npmignore will allow npm to move the `lib` folder when we do local development. Not sure it is the best way to solve the problem. Feel free to abandon it for better solutions.

### CODE REVIEW

**Comment by maysale01** [comment]
@wangmengyan95 I think the preferred method for handling this is to add a "prepublish" npm script for running the build.

**Comment by drew-gross** [comment]
Even though I also develop under `parse-server-example` I also feel this is a little janky. Maybe it would be better to have an "official" local development instantiation of the server in the `parse-server` repo. We could maybe even add an `npm develop` command or something like that. Thoughts?

**Comment by maysale01** [comment]
I think this is the canonical way. Npm defaults to gitignore if there is no
npm ignore.

**Comment by nlutsenko** [comment]
Agreed with the fact that this is a canonical way, we probably also should ignore `spec` and `src` in it, so we don't deploy tests and non-compiled source via npm.

**Pull request merged**
