### PR TITLE
Simple SendGrid email adapter

### PR DESCRIPTION
**Pull request by carmenlau**
Using https://github.com/sendgrid/sendgrid-nodejs

### CODE REVIEW

**Comment by gfosco** [comment]
We'd prefer that more adapters (and even the ones we have now) be moved to separate NPM packages.  `parse-server-sendgrid` could be a good name for this one.  It would be easier to `require('parse-server-sendgrid')` than `require('parse-server/lib/Adapters/Email/SimpleSendgridAdapter')`

**Comment by noder199** [comment]
@gfosco How are we supposed to find/setup these adapters?

**Comment by gfosco** [comment]
Through NPM, and through our wiki.. I've also thought about building a search/discovery spot for parse-server modules.

**Comment by carmenlau** [comment]
I have put this to npm and I am going to close this PR.
https://www.npmjs.com/package/parse-server-sendgrid-adapter

Search/discovery spot for parse-server modules are good idea. Thanks all for your help.

**Comment by zeluspudding** [comment]
Does the adapter support SendGrid's email templates?

**Comment by gowridev** [comment]
when sendgrid-adapter module is added to parse server git master?

**Comment by zeluspudding** [comment]
@noder199, were you able to get this adapter setup? I did however I'm clearly not initializing two variables as shown below in a test password reset email (one the app name the other the app's domain name). I've tracked the trigger for this email down to the `defaultResetPasswordEmail` function located in parse server's `.\node_modules\parse-server\lib\Controllers\UserController.js` within the `UserController` class. My question is, and perhaps @carmenlau can answer this, how does one set the `appName` and domain to properly generate emails? Any help is appreciated

sendgridtest1

**Comment by kalitas** [comment]
@zeluspudding did you manage to succeed with the password reset ? should i use the sendgrid adapter?

**Comment by zeluspudding** [comment]
I ended waiting for the code to mature but then our project got cancelled so, unfortunately, no :( Wish I could help ya

**Pull request closed without merging**
