### PR TITLE
Allow crossdomain on filesRouter

### LINKED ISSUE #875: Parse Server doesn't issue correct headers for attempts to upload files
This breaks file uploading in Parse Dashboard.

### PR DESCRIPTION
**Pull request by flovilmart**
Fixes #875

### CODE REVIEW

**Comment by dvanwinkle** [comment]
@flovilmart Thank you, thank you, thank you!

**Comment by flovilmart** [comment]
:beers:

**Comment by dcdspace** [comment]
I updated my server and dashboard but still got the same error when trying to upload an image.

**Comment by flovilmart** [comment]
Yeah,you most likely need to wait

**Pull request merged**
