### PR TITLE
Adding a test to demonstrate #1238

### PR DESCRIPTION
**Pull request by airdrummingfool**

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
@airdrummingfool updated the pull request.

**Comment by airdrummingfool** [comment]
I moved the test case to the new `CloudCode.spec.js` test file.

**Comment by drew-gross** [comment]
Oh awesome thank you. I'm working on #1844 right now, I'll do this one right after.

**Comment by drew-gross** [comment]
Merged into #1884, which also fixes the issue.

**Pull request closed without merging**
