### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by didierfranc**
It should be good to have a **Dockerfile** here to have an automated image on docker hub from the official Parse-Server repo !

### CODE REVIEW

**Comment by maysale01** [comment]
It's bad practice to bake the environment variables into the image. I think @flovilmart is working on a CLI, which would make sense to use as the **ENTRYPOINT**.

**Comment by flovilmart** [comment]
I'm effectively working on some CLI system and also support for multiple apps and cloud code instances.
That is quite a big PR, as Cloud Code needed to run in subprocess to have proper isolation.

As a good side effect, we now have automated hooks registration upon declaration :)
The docker file should have

```
COPY ./config.json config.json
RUN npm start -- --config ./config.json
```

**Comment by maysale01** [comment]
@flovilmart I'd say even doing a `COPY` of a secrets file into the image would be risky. You should b
build the image and then supply the secrets during `docker run`. I think it'd be cool if the Dockerfile used a CLI:
```
ENTRYPOINT ['bin/cli']
# Default CMD
CMD ['start', '--config default.json']
```
You can then pass commands to the image on dockerhub, i.e.
```
// Pass in config as environment variables
docker run parse-server:latest start -ddatabaseURI=mongodb://databasehost.com/12345
```
```
// Load config from S3 bucket
docker run parse-server:latest start --config s3://mybucket.amazons3.com/configs/1.json?signature=XXX
```
```
// Pass configs as JSON string
docker run parse-server:latest start --config "{appId: 12345, databaseURI: mongodb://databasehost.com/12345'}"
```
```
// Mount configs from local
docker run -v /configs:/var/app/configs/ parse-server:latest start --config /var/app/configs/main.json
```

Could launch an instance of the server with 1 line. If you're feeling ambitious, the CLI could also manage installing/registering Parse modules, similar to how the `Ember CLI` does.

**Comment by flovilmart** [comment]
@mysale01, I'm pretty new to docker, and yes copy the config.json is not possible as for the base image as it's not there :)

As of today, the base CLI is there on master under `bin/parse-server` with the support of environment.

**Comment by gfosco** [comment]
Can we create a `contrib/` folder and move this in there (and update it to work from the subfolder)?  Supportive of the idea, but not sure we want to commit to supporting it / testing it / ensuring it doesn't break in the future.

**Comment by maysale01** [comment]
Docker files have to be run at the project root because only subdirectories
are included in the docker context. I don't think this is production worthy
at the moment, the environment variables need to be removed. It should
essentially just be a 3 line file to run NPM install and have a default
command like "forever bin/server".

**Comment by flovilmart** [comment]
:+1: @maysale01

**Comment by gfosco** [comment]
In that case, we'll close this.  If there's use in having a simpler one, let us know.

**Pull request closed without merging**
