### PR TITLE
Update PostgresStorageAdapter.js

### PR DESCRIPTION
**Pull request by vitaly-t**
* correcting some queries
* correcting spellings
* adding notes

### CODE REVIEW

**Comment by drew-gross** [comment]
It looks like this PR changes the whitespace for the entire file, maybe your editor did that automatically. Could you undo that? It both makes it hard to tell what actually changed, and make `git blame` a lot less useful.

**Comment by vitaly-t** [comment]
Damn, I've made so many small changes, and to get get rid of the changed white spaces I would have to re-do everything. That sucks.

Do you have tests for that to confirm the correctness?

**Comment by Zeraceee** [comment]
@vitaly-t shift-tab is your friend, can't you simply fix that with a formatter/linter/manually in no time?

**Comment by drew-gross** [comment]
Yep, I don't know what editor you are using, but in sublime text you can just set the indentation level and then re-indent everything.

We have fairly comprehensive tests so I'm pretty sure your code is correct, but I'd like to look at what exactly changed as well, which is hard when the whitespace changes make it look like everything chagned. If you don't want to do it, I could do the re-indentation myself, but you would lose attribution.

**Comment by vitaly-t** [comment]
I'm using WebStorm. I would pay better attention to it next time, but re-doing all changes now is kind of late :|

**Comment by blacha** [comment]
It looks like you have just switched the file from 2 space indenting to 4 space indenting, if you just reformat it back into two space indenting and commit that the diff should then work ok?

**Comment by Zeraceee** [comment]
@vitaly-t http://pastebin.com/raw/qnTYnbBJ

Simply paste that into your IDE for the file and recommit, it fixes the whitespace.

**Comment by drew-gross** [comment]
No problem, I'll close this and apply the same changes in a new PR.

**Pull request closed without merging**
