### PR TITLE
Use the Postgres Adapter with a Postgres URI

### PR DESCRIPTION
**Pull request by kulshekhar**
This PR gets Parse Server to use the Postgres adapter if the `--databaseURI` supplied is of the form `postgres://...`.

### CODE REVIEW

**Comment by lsxredrain** [comment]
how to config postgres for parse-server?

**Comment by kulshekhar** [comment]
@lsxredrain when starting parse server, specify the `--databaseURI` in this format `postgres://username:password@host:port/db-name`

You can also add another `--databaseOptions` parameter which should be a JSON object. The fields in this object will override those set in the `--databaseURI`. The values that you can set in this object are `user`, `password`, `poolSize`, `host`, `port`, `database`, `ssl`, `binary`, `client_encoding`, `application_name` and `fallback_application_name`

**Comment by flovilmart** [comment]
Replace he databaseURI by one that starts with postgres and points to your database.

Note that you have to use the latest build by pointer to "parseplatform/Parse-server#latest" in your package.json

**Comment by lsxredrain** [comment]
@flovilmart  thanks a lot, I try it

**Comment by lsxredrain** [comment]
name: 'error',
length: 108,
severity: 'ERROR',
code: '42703',
detail: undefined,
hint: undefined,
position: '33',
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'parse_relation.c',
line: '3090',
routine: 'errorMissingColumn' } error: column "password" does not exist
at Connection.parseE (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js: 539:11)
at Connection.parseMessage (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connecti on.js:366:17)
at Socket. (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js :105:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:543:20)
error: column "password" does not exist
at Connection.parseE (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js: 539:11)
at Connection.parseMessage (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connecti on.js:366:17)
at Socket. (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js :105:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:543:20)

**Comment by yogeshwaranManoharan** [comment]
Error while starting out, i opened a issue please check it [https://github.com/ParsePlatform/parse-server/issues/3595](url)

**Comment by acinader** [comment]
fixes #3595

**Pull request merged**
