### PR TITLE
Adds ability to override mount with publicServerURL for production uses

### LINKED ISSUE #1131: GridStoreAdapter files location
Because of https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Files/GridStoreAdapter.js#L66 when using nginx (or other) to proxy requests, you don't have enough control over the files location url.

My suggestion is to use like it currently is as a default behavior but add an optional parameter in the GridStoreAdapter to set the file location (instead of the default config.mount).

I would like to know if a contribution about it would be welcome.

### PR DESCRIPTION
**Pull request by flovilmart**
superseds #1270
fixes #1131 

also adds a sanity so we don't keep trailing / in mount or publicServerURL

### CODE REVIEW

**Comment by drew-gross** [comment]
I think we actually don't want to do this, since we don't really want internal queries to go back out to the public internet to do dns resolution and so on.

**Comment by flovilmart** [comment]
We only use .mount to give back to the clients (and in file adapters)

**Comment by flovilmart** [comment]
``` 
RestWrite.prototype.location = function() {
  var middle = (this.className === '_User' ? '/users/' :
                '/classes/' + this.className + '/');
  return this.config.mount + middle + this.data.objectId;
};
```

**Comment by drew-gross** [comment]
Ah right this is only for the mount point, not the URL. In that case this looks good.

**Comment by flovilmart** [comment]
This is the full URL that is returned to the clients, mount is currently inferred :

``` 
function handleParseHeaders(req, res, next) {
  var mountPathLength = req.originalUrl.length - req.url.length;
  var mountPath = req.originalUrl.slice(0, mountPathLength);
  var mount = req.protocol + '://' + req.get('host') + mountPath;
...
```

**Pull request merged**
