### PR TITLE
Incorporate vitaly-t changes

### PR DESCRIPTION
**Pull request by drew-gross**
@vitaly-t this is the replacement PR. Everything looks good to me. Thanks for the help! Tests already passed on the original PR so I will merge right away.

### CODE REVIEW

**Comment by vitaly-t** [comment]
@drew-gross 

I don't know the role of this piece of code, but does it need performance and efficiency, or those are not important in this context?

I'm asking to see what other improvements might be worthwhile adding, because on the overall there could be too many ;)

**Comment by drew-gross** [comment]
Cool! This is definitely a performance-critical part of the system. `getClass`, `updateObjectsByQuery`, and `deleteObjectsByQuery` are probably the most critical. Of course, there are still many unimplemented parts, so until those are implemented there won't be much benefit in making stuff faster.

**Comment by vitaly-t** [comment]
Great! Let me know if you have any questions, I will be happy to help!

In the meantime, the biggest omission I've seen in the code is in trying to generate inserts and updates without doing it automatically, with methods in the [helpers](http://vitaly-t.github.io/pg-promise/helpers.html) namespace, which is exactly what it was implemented for ;)

**Comment by vitaly-t** [comment]
P.S. Although, if it already works, then it's not that important, just for the future ;)

**Comment by drew-gross** [comment]
That looks really useful, I will check out the helpers namespace. Awesome.

I prefer the long-form names, actually. Otherwise you can end up with strings of like 10 symbols in a row, which I think is harder to read.

**Pull request merged**
