### PR TITLE
Improve update of jsonb fields. Add PG 9.5 to travis.

### PR DESCRIPTION
**Pull request by kulshekhar**
This PR changes the travis config and updates of jsonb fields in the following manner:

Travis:
- use Postgres 9.5
- set `sudo` to `required`
- replace the `precise` distribution with `trusty` 

The last two changes are required because Travis doesn't seem to have a simple way of using Postgres 9.5 with precise (with or without sudo) and it needs [sudo on trusty](https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version)

Update of `jsonb` fields
- for a normal update, the new object is merged with the existing object
- for an update that specifies field(s) should be deleted, the update deletes the specified fields and merges the rest of the object.

This PR also enables one existing test to run against Postgres

### CODE REVIEW

**Comment by flovilmart** [comment]
You're on fire!

**Comment by kulshekhar** [comment]
Given that the alternative would be to build something eerily similar to parse server (using postgres instead of mongodb), I'm just trying to do what I can to make parse server work with Postgres :smile:

**Comment by flovilmart** [comment]
Eheh the bases are pretty solid! Thanks for all your contributions and the ones to come!

**Comment by flovilmart** [comment]
tests seem to fail on travis but I can't see the logs :/

**Comment by kulshekhar** [comment]
same here. It's happening with some other repos too.

**Comment by kulshekhar** [comment]
For the postgres specific builds that fail, it's a bit weird. If it doesn't fail on both 4.5 and 6.1, chances are that rebuilding the test for the failed version will pass

**Comment by flovilmart** [comment]
Looking 👍

**Pull request merged**
