### PR TITLE
Auth._loadRoles should not query the same role twice.

### PR DESCRIPTION
**Pull request by blacha**
This fixes bug #1365 By not triggering a ``_getAllRoleNamesForId`` for roleID's that have already been queried.

### CODE REVIEW

**Comment by flovilmart** [comment]
Very cool!

**Comment by flovilmart** [comment]
What happens when new roles are created and added into the hierarchy or removed from the hierarchy?

**Comment by blacha** [comment]
Its on a per ``Auth._loadRoles`` caching, so each new request will still do the full new query.

It is just trying to limit the same query from happening multiple times in the ``Auth._loadRoles``

**Comment by flovilmart** [comment]
Alright! LGTM!

**Comment by blacha** [comment]
It would probably be a good idea to sometime in the future cache the results of these ``_loadRoles`` on a per user basis, in my application right now I can get upwards of 1000 ``_Role`` queries in a single query. Not too sure how Parse.com did it, but it was much faster on there than it is on ParseServer

**Comment by flovilmart** [comment]
Caching is quite a challenge in a distributed environment. But we definitely should look into it.

**Comment by flovilmart** [comment]
That being said, the Cache class could support easily role hierarchies, and we could invalidated the same way we invalidate users. If that's something you wanna tackle, feel free to get going.

**Comment by blacha** [comment]
This commit actually solves most of our performance problems with Roles in our production environment :)

It would be tricky to trigger cache invalidations on multiple VM's when a one VM changes a Role or User.

Looking of the invalidation code you have already for the User, you would run into this problem when you have more than one instance of the ParseServer.

Do you have anywhere where devs on this project talk (Gitter/IRC/Slack/?), as talking more about this  here isnt really ideal.

**Comment by flovilmart** [comment]
Shoot me a mail.

**Pull request merged**
