### PR TITLE
Become on non existing user

### PR DESCRIPTION
**Pull request by flessard**
Fix bug where become return invalid session if the pointer to user
doesn't exist

### CODE REVIEW

**Comment by flovilmart** [comment]
We may wanna destroy the session instead no? @drew-gross what do you think?

**Comment by drew-gross** [comment]
Destroying session for deleted user seems to make sense, yes. Have you checked what Parse.com does? Also I recall some issue where the SDKs would start failing when their session was destroyed, so maybe that's why we didn't destroy it.

**Comment by flovilmart** [comment]
If user is deleted, session token should be invalidated at least. @flessard can you check the current behavior on parse.com or you want me to check it out?

Other thing to check is to see when calling include on a key and the included object don't exist. Should the pointer getting soft-deleted from the response? I would tend to say so.

**Comment by flessard** [comment]
@flovilmart Yes if you can check it out, i would appreciate it.

I agree whit you @flovilmart, if the pointer getting don't exist, Should soft-deleted from the response.

**Comment by flovilmart** [comment]
@flessard so I can confirm that missing includes are resolved to undefined, and that the pointer object is not forwarded to the client.

**Comment by flovilmart** [comment]
Superseded by #777

**Pull request closed without merging**
