### PR TITLE
Adds maxUploadSize option

### PR DESCRIPTION
**Pull request by flovilmart**
Fix for #536

### CODE REVIEW

**Comment by tanmays** [comment]
Super! 👍

**Comment by flovilmart** [comment]
tests seems failing for weird reasons.

@tanmays can you test that branch? I blindly followed what you suggested :)

**Comment by tanmays** [comment]
@flovilmart just gave a quick test and tried uploading an image to S3, it works! :)

**Comment by flovilmart** [comment]
@tanmays thanks! :tada:

**Comment by drew-gross** [comment]
LGTM. Probably we should document this new option somewhere too.

**Comment by flovilmart** [comment]
I'll document it with proper-cli if you merge that one :)

**Pull request merged**
