### PR TITLE
bumps mongo-runner with fix for stalling downloads

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by gfosco** [comment]
Still failing with a lot of index errors..

**Comment by flovilmart** [comment]
Yeah, I noticed that too... That's real odd. On your machine too?

**Comment by gfosco** [comment]
Locally I only got one failure, 'httpRequest should get a cat image' timed out.

**Comment by flovilmart** [comment]
maybe the cat API is blocking for too many requests.... just tried with 3.1.17 and it works... 3.2.0 seems borked for some reason (that's my contrib), but all tests are passing

**Comment by flovilmart** [comment]
@iamlucas we have issues here too for some reason since we bumped mongodb-runner

**Comment by flovilmart** [comment]
closing as it borked

**Pull request closed without merging**
