### PR TITLE
FIX #1572 - Accepting LOGS_FOLDER as env variable

### LINKED ISSUE #1572: [2.2.7] Logs path is absolute?
I'm using the latest versione of Parse-Server and I keep getting this error:

```
Error: EACCES: permission denied, open '/logs/parse-server.info.2016-04-20'
    at Error (native)
``` 

It seems that the logs path is absolute and not relative to the project, and the logs are created in the absolute path /logs/. My Parse instance is running through foreverjs, maybe this helps?

### PR DESCRIPTION
**Pull request by KartikeyaRokde**
This fixes the issue #1572 

Accepting LOGS_FOLDER from environment variable will help developers to set logs folder as they require.

### CODE REVIEW

**Comment by drew-gross** [comment]
Thanks for the PR! We mostly use a convention of prefixing our env vars with `PARSE_SERVER_*`, could you do that with this one as well please? Also, a note in the docs would be nice :)

**Comment by KartikeyaRokde** [comment]
Hi, Will make the changes. A Note in /wiki/Parse-Server-Guide will be good to go or should it be in any other docs?

**Comment by facebook-github-bot-6** [comment]
@KartikeyaRokde updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@KartikeyaRokde updated the pull request.

**Comment by KartikeyaRokde** [comment]
Hi Team, there's Mongo authentication error for all the CI builds for **Node.js: 6.1** and **MONGODB_VERSION=3.0.8**. ``

`MongoError: Authentication failed.`

I think the mongoDB is not configured with authentication. Can you please have a look in this.

**Comment by drew-gross** [comment]
I restarted the build and it passed. Merging.

**Pull request merged**
