### PR TITLE
Fix for related query on non-existing column

### PR DESCRIPTION
**Pull request by gfosco**
This will finally address #280 and #286.

### CODE REVIEW

**Comment by flovilmart** [comment]
The role is expected to have a relation to users in the schema, mind to add the same test with a random object, and non existing relation key?

**Comment by drew-gross** [comment]
I agree with @flovilmart, I don't think the test you added actually tests this change. That said, it's also a simple change so I'd say feel free to merge anyway.

**Comment by gfosco** [comment]
The test fails without the change, so it does work..

**Comment by drew-gross** [comment]
Actually that does make sense, since the relation will only be in the _SCHEMA object, the collection won't actually be created.

**Comment by flovilmart** [comment]
oh right !

**Pull request merged**
