### PR TITLE
Adding Sentry exception logging to Parse server

### PR DESCRIPTION
**Pull request by ehfeng**
Happy to also provide documentation on spinning up the open source [Sentry server](https://docs.getsentry.com/on-premise/), for those wanting to run that themselves as well.

### CODE REVIEW

**Comment by gfosco** [comment]
I'm not in love with the implementation... Maybe you could abstract out a LogAdapter instead, and have it be a module you inject.

**Comment by ehfeng** [comment]
Sure, thanks for the tip. Looks like I have some weekend coding. :coffee:

**Comment by ehfeng** [comment]
Could you point me to an example in the code of a similar abstraction?

**Comment by gfosco** [comment]
I'd say look at FilesAdapter and GridStoreAdapter.. let me know if you have questions.

**Comment by gfosco** [comment]
A logging adapter will be added in #243 and you can build a Sentry adapter for that.  Thanks! :+1:

**Pull request closed without merging**
