### PR TITLE
Concat appId to PubSub channel

### PR DESCRIPTION
**Pull request by davimacedo**
It would allow to run multiple live query servers in same redis.

### CODE REVIEW

**Comment by flovilmart** [comment]
Seems to be missing the counter part for the publisher?

**Comment by davimacedo** [comment]
No.. it is in the following file:
src/LiveQuery/ParseCloudCodePublisher.js

**Comment by davimacedo** [comment]
Sure. What's the next release?

**Comment by flovilmart** [comment]
I'll take care of it :)

**Comment by davimacedo** [comment]
Thanks!

**Pull request merged**
