### PR TITLE
Prevent allowCrossDomain middleware from sending headers if they're already sent

### PR DESCRIPTION
**Pull request by sebsylvester**
This fix solved the [issue #2410](https://github.com/ParsePlatform/parse-server/issues/2410) for me

### CODE REVIEW

**Comment by flovilmart** [comment]
While this should be working, this is not the correct fix for that issue i believe. The problem comes from the way we mount our routes for the PublicAPIRouter, and the way it falls through to the middlewares after mounting those

**Comment by sebsylvester** [comment]
You're right, it's not a clean fix. I wanted to bring the issue to people's attention because I was surprised so few reported the same kind of issue with the sent headers. Shouldn't there be a "headers sent" check between the PublicAPIRouter and the middlewares like allowCrossDomain?

**Comment by flovilmart** [comment]
There are 2 kinds of problems related to the sent headers:

1. the one you describe on those endpoints, where we want to exit early
2. When using parse-server as an express module alongside other middlewares

I'm trying to figure out something, as this middleware suite is not supposed to be run at all as the endpoints are not matching after.

**Comment by flovilmart** [comment]
Should be fixed by #2475

**Pull request closed without merging**
