### PR TITLE
Remove mongoFind and mostly remove adaptiveCollection

### PR DESCRIPTION
**Pull request by drew-gross**
We are getting to be super close to an that is well defined enough that we can build adapter for other DBs.

### CODE REVIEW

**Comment by flovilmart** [comment]
The commit log is really good?

**Comment by drew-gross** [comment]
Hence why we squash now, mostly :p

**Comment by facebook-github-bot-9** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@drew-gross updated the pull request.

**Pull request merged**
