### PR TITLE
Enable a few tests to test against Postgres

### PR DESCRIPTION
**Pull request by kulshekhar**

### CODE REVIEW

**Comment by kulshekhar** [comment]
This build is failing because a [particular postgres operator](https://github.com/ParsePlatform/parse-server/pull/2971/files#diff-b0af2ee2c26859a8aa6d8d0a0cf3a64aR897) (`||`) used was introduced in version 9.5. 

Would it be acceptable to set this as the minimum supported postgres version?

**Comment by flovilmart** [comment]
Yeah, bump to 9.5. We also have the functions that could be simplified as 9.5 introduces some of nice things.

Also, you can remove from the .travis.yml the allowed failures ;)

**Comment by kulshekhar** [comment]
It might be a bit early to remove Postgres from allowed failures. There are some tests (related to Cloud Code) that fail randomly. I'm trying to find the source of that but haven't been able to do so yet.

**Comment by flovilmart** [comment]
alright! We'll need to update the docs for this new minimal version

**Comment by kulshekhar** [comment]
I didn't know we had docs for Postgres :smile:

**Comment by kulshekhar** [comment]
Finally :sweat:

**Pull request merged**
