### PR TITLE
Fixes #1649

### LINKED ISSUE #1649: `validateEmailConfiguration` should be called when sending reset password email
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.2.7 on Heroku

#### Steps to reproduce
- Configure an Email Adapter in index.js
- **Don't** configure app name and/or public server URL
- Request a reset password email via `requestPasswordReset`

#### Result
Users will receive an email with title "Password reset for **undefined**", and body:

"You requested to reset your password for **undefined**. Click here to reset it: **undefined**/apps/....."

#### Expected Result

[`validateEmailConfiguration`](https://github.com/ParsePlatform/parse-server/blob/d33dd68cc521e63be68a93ab1a00cfdb7a7d243d/src/Config.js#L75) or some variation of it should be called before sending reset password emails, to make sure that both app name and public server url were set correctly.

### PR DESCRIPTION
**Pull request by drew-gross**

### CODE REVIEW

**Comment by natanrolnik** [comment]
Thanks for the PR of this test, @drew-gross. I think I wasn't clear in my description in #1649
I was describing a case when you **do have** an Email Adapter, but `verifyUserEmails` **is not set, or set to `false`**. In this case, `validateEmailConfiguration` is not called, but sending an e-mail that uses `publicServerURL` and `appName` may still happen if the server receives a call to `/requestPasswordReset`.
This way, the test would be defined as something like this:

```
it('fails if sendPasswordResetEmail is called, without setting an app ID or publicServerURL, and verifyUserEmails is not set or set to false (regression test for #1649)', done => {
```

**Comment by drew-gross** [comment]
Got it, will fix, thanks.

**Comment by facebook-github-bot-9** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@drew-gross updated the pull request.

**Comment by natanrolnik** [comment]
Looks good, that's exactly what I meant.

**Comment by drew-gross** [comment]
Unfortunately the tests are failing, and I can't figure out why, so I can't merge this yet :(

**Comment by flovilmart** [comment]
All tests a good!

**Comment by flovilmart** [comment]
LGTM!

**Pull request merged**
