### PR TITLE
Fix logic for missing geo index error message check

### PR DESCRIPTION
**Pull request by TylerBrock**
This will get the ParseGeoPoint.spec tests passing with MongoDB 3.2

### CODE REVIEW

**Comment by drew-gross** [comment]
Sweet. What was the change in Mongo that made this change necessary?

**Comment by TylerBrock** [comment]
None, the logic was just wrong :-)

**Comment by TylerBrock** [comment]
The second condition was never checked with the || and so even though there was a match for that error message in MongoDB 3.2 when the index is missing it still threw.

You might be wondering why the error code changed or is missing now, that I don't know.

**Comment by TylerBrock** [comment]
Actually I guess there was a small change in how a missing geo index is reported (sans error code) but the original intent of this code would have cought that I think.

**Comment by drew-gross** [comment]
Interesting. Error codes are something I would expect to not change between versions. Well, feel free to merge whenever you want.

**Comment by TylerBrock** [comment]
I might do some more digging and file a JIRA ticket about this instead.

**Comment by TylerBrock** [comment]
Submitted: https://jira.mongodb.org/browse/SERVER-24198

**Pull request merged**
