### PR TITLE
Add Gitter chat link to the README.

### LINKED ISSUE #1700: Group chat for repository (Gitter)
I noticed that a lot of tasks are created just to discuss or ask some question. It would be probably better to use group chat for that, something like Gitter or Slack. I think Gitter would be better, because it stores chat logs forever.

I checked that you were asked for having Gitter chat already in #566 and #1366.

Setting up channel in Gitter is pretty straightforward. Let me know if you need any help with it.

### PR DESCRIPTION
**Pull request by nlutsenko**
Closes #1700

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
@nlutsenko updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@nlutsenko updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@nlutsenko updated the pull request.

**Comment by flovilmart** [comment]
LGTM!

**Comment by facebook-github-bot-8** [comment]
@nlutsenko updated the pull request.

**Pull request merged**
