### PR TITLE
WIP: Troubleshooting #2275

### PR DESCRIPTION
**Pull request by flovilmart**
Extends test to make sure _PushStatus is not part of the _Schema

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@flovilmart updated the pull request.

**Comment by drew-gross** [comment]
This test should really go to the mongo client directly, as the mongo adapter does some stuff to handle the removal of the legacy data inside the adapter.

**Comment by flovilmart** [comment]
Ok!

**Comment by facebook-github-bot-2** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @drew-gross as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by flovilmart** [comment]
The issue don't reproduce anymore, closing

**Pull request closed without merging**
