### PR TITLE
Exposes the ClientSDK infos if available

### PR DESCRIPTION
**Pull request by flovilmart**
This PR is required for #1946 in order to only provide the Delete op with valid SDK's.

### CODE REVIEW

**Comment by flovilmart** [comment]
@nlutsenko, @drew-gross recommended that I give that one to you.

**Comment by nlutsenko** [comment]
Yup, this looks a-ok. Did you test with the latest iOS SDK by any chance?
Is all of the info properly visible?

**Comment by flovilmart** [comment]
I checked the code, and that seems to be what's sent out: 

https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/a0372136fcc51ba84a5d8f065966ee6fea9b95de/Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m#L137

**Comment by nlutsenko** [comment]
Sounds good. Merging.

**Pull request merged**
