### PR TITLE
add digits oauth provider

### PR DESCRIPTION
**Pull request by ranhsd**
pull request for issue #2280

### CODE REVIEW

**Comment by flovilmart** [comment]
Did you try it?

**Comment by ranhsd** [comment]
Hi @flovilmart yes and it worked. In order to use it you need to specify "digits" in the provider name and send the token, secret token and digits user id. 

in iOS it looks like: 

```
    [[Digits sharedInstance] authenticateWithViewController:nil configuration:configuration completion:^(DGTSession *session, NSError *error) {
        if (error) {
            return;
        }

        [PFUser registerAuthenticationDelegate:self forAuthType:@"digits"];
        
        [[PFUser logInWithAuthTypeInBackground:@"digits" authData:@{@"auth_token" : session.authToken,@"auth_token_secret" : session.authTokenSecret,@"id" : session.userID}] continueWithBlock:^id _Nullable(BFTask<__kindof PFUser *> * _Nonnull task) {
            
            if (task.error){
                NSLog(@"error occured %@",task.error);
            }
            
            return nil;
        }];
    }];
```

**Comment by jeveloper** [comment]
THanks for awesome work, curious if anyone uses auth0 with parse-server and what would be the better practice to make it work together.
I assume i can store anything in authData

**Comment by benitech** [comment]
@ranhsd Would it be possible to also add the verified email that Digits provides from the authenticated user directly into the Parse "email verified" field?

Something similar to this - https://github.com/felix-dumit/PFUser-Digits/blob/master/user.js

**Comment by flovilmart** [comment]
@benitech not sure we're gonna rely on those provided fields automatically as we're using those providers for identity and authentication purposes. also it's very easy to include that into a beforeSave to fill up a user's info.

**Comment by JulliardK** [comment]
Hello, 

I hope I'm not a bother, I'm still learning and need some help with this.

How I went about trying to integrate digits with Parse server is this:
1. downloaded the SDK from parse
2. pod installed parse, fabric and digits 
3. pulled and dropped these files into my workspace: https://github.com/felix-dumit/PFUser-Digits
4. followed the "digits for iOS" installation guide: https://fabric.io/kits/ios/digits/install

the issue i faced was **shell script invocation error** when i added a _run script build phase_ which was the second step in the "digits for iOS" installation guide.

am i not getting the steps right? i'm really sorry if this is such a simple question.

*oh right, could it be that i'm writing the code in _swift_ but the files I pulled in (**step 3**) was written in objC? 

I'm really stuck, please help me out.

thank you!

**Pull request merged**
