### PR TITLE
Adding the GCP logo and quickstart

### PR DESCRIPTION
**Pull request by mcdonamp**
Jumping on the bandwagon here and adding the [Google Cloud Platform Parse Server quickstart](https://cloud.google.com/nodejs/resources/frameworks/parse-server).

### CODE REVIEW

**Comment by mcdonamp** [comment]
Looks like the CI issue is the flaky GeoPoint test in #588.

**Comment by drew-gross** [comment]
Yep, just a flaky test. Merging anyway.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
