### PR TITLE
Add serverURL environment variable for bin-script

### PR DESCRIPTION
**Pull request by merowinger92**
updated newly added environment varibale PARSE_SERVER_SERVERURL

### CODE REVIEW

**Comment by gfosco** [comment]
Let's do this in one PR, I'll close the other.  Please use `PARSE_SERVER_URL` as the variable name.  Thanks for catching this, it could be one of the bigger stumbling blocks if people are running the server this way...

**Comment by flovilmart** [comment]
@gfosco people are updating the bin/parse-server directly... I'm thinking using commander for the CLI to obfuscate everything as this mis-usage is plain wrong.

**Comment by flovilmart** [comment]
@gfosco @merowinger92 I'm pushing it further in #603

**Comment by gfosco** [comment]
Closing this since things are changing to a nice cli..

**Pull request closed without merging**
