### PR TITLE
exposes features through package.json

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by drew-gross** [comment]
I think putting EVERYTHING in the package.json is a little heavy handed. I'd say only stuff that is supported purely by the server and doesn't require adapters should go in there.

**Comment by gfosco** [comment]
I'm not a fan of putting this stuff in package.json, but won't stop yas from doing it...

**Comment by drew-gross** [comment]
@gfosco what we were planning here was to have a way for the dashboard to know what features you could get if you upgrade your server. We can discuss more tomorrow, I won't merge until then.

**Comment by drew-gross** [comment]
The stuff about the dashboard knowing what features you could get if you upgrade is going to part of the dashboard only, so I'm going to close this.

**Pull request closed without merging**
