### PR TITLE
Installation push tracking

### PR DESCRIPTION
**Pull request by alexblack**
Records push status per Installation, in a new class `Push` with fields:

- installation
- pushStatus
- result
- deviceToken

Logic:

1. A new Push object is created for each (Installation, PushStatusId) when sending pushes to the push adapter
2. After the push adapter returns, each of those objects is updated with a result

Result scenarios for each push:

1. No deviceToken found on installation
2. No result from adapter for installation
3. Result from adapter

### CODE REVIEW

**Comment by alexblack** [comment]
`npm run test` passed locally, but looks like there is an issue causing a test to fail. I'll look at fixing that up.

**Comment by flovilmart** [comment]
Seems that your fixes break compatibly with the postgres adapter...

**Comment by alexblack** [comment]
Yes :(  Is there a way for me to test that out locally?  It seems that `npm run test` didn't catch the problem for me.

**Comment by alexblack** [comment]
I'm trying for the first time to run the postgres tests locally, hitting an issue, not sure if this is due to my code or not yet.

```
Alexs-MacBook-Pro:parse-server alex$ npm test

> parse-server@2.2.23 test /Users/alex/dev/parse/parse-server
> cross-env MONGODB_VERSION=${MONGODB_VERSION:=3.2.6} MONGODB_STORAGE_ENGINE=mmapv1 NODE_ENV=test TESTING=1 node $COVERAGE_OPTION ./node_modules/jasmine/bin/jasmine.js

Started
............................................Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfig.json
...Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfigApps.json
.................................*.......................*.....................*............................................................................................................*...............................................................................................................................*......................................FFFFFFFFFFFF......F................................*........*....................................................................*.............................*..........*.........*.............../Users/alex/dev/parse/parse-server/spec/ParseObject.spec.js:1942
      expect(array[2].get("key").get("foo")).toEqual("bar");
                      ^

TypeError: array[2].get is not a function
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/spec/ParseObject.spec.js:1951:23)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at /Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:219:35
    at runLater (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:203:12)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:218:9)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:162:22)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:168:27)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:168:27)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at xhr.onreadystatechange (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/RESTController.js:115:21)
    at dispatchEvent (/Users/alex/dev/parse/parse-server/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
npm ERR! Test failed.  See above for more details.
```

**Comment by alexblack** [comment]
I'm having a bit of trouble getting the postgres tests to pass locally, I'd appreciate any input or suggestions, I'm still looking into it.

```
#!/bin/sh
dropdb parse_server_postgres_adapter_test_database
psql -c 'create database parse_server_postgres_adapter_test_database;' -U postgres
psql -c 'CREATE EXTENSION postgis;' -U postgres -d parse_server_postgres_adapter_test_database
psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d parse_server_postgres_adapter_test_database
export PARSE_SERVER_TEST_DB=postgres
export CODE_COVERAGE=1
export PARSE_SERVER_TEST_TIMEOUT=20000
export COVERAGE_OPTION='./node_modules/.bin/istanbul cover'
echo "node --version"
node --version
echo "psql --version"
psql --version
git checkout master
npm test
```

```
Alexs-MacBook-Pro:parse-server alex$ ./test.sh
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
node --version
v4.4.7
psql --version
psql (PostgreSQL) 9.5.3
Already on 'master'
Your branch is up-to-date with 'origin/master'.

> parse-server@2.2.23 test /Users/alex/dev/parse/parse-server
> cross-env MONGODB_VERSION=${MONGODB_VERSION:=3.2.6} MONGODB_STORAGE_ENGINE=mmapv1 NODE_ENV=test TESTING=1 node $COVERAGE_OPTION ./node_modules/jasmine/bin/jasmine.js

Started
............................................Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfig.json
...Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfigApps.json
.................................*.......................*.....................*............................................................................................................*...............................................................................................................................*.........................................................................................*........*....................................................................*.............................*..........*.........*...............File [/Users/alex/dev/parse/parse-server/src/Adapters/Files/FilesAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Cache/CacheAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Email/MailAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Push/PushAdapter.js] ignored, nothing could be mapped

=============================== Coverage summary ===============================
Statements   : 70.73% ( 4995/7062 )
Branches     : 60.96% ( 2539/4165 )
Functions    : 69.28% ( 832/1201 )
Lines        : 70.65% ( 4803/6798 )
================================================================================
/Users/alex/dev/parse/parse-server/spec/ParseObject.spec.js:1942
      expect(array[2].get("key").get("foo")).toEqual("bar");
                      ^

TypeError: array[2].get is not a function
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/spec/ParseObject.spec.js:1951:23)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at /Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:219:35
    at runLater (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:203:12)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:218:9)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:162:22)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:168:27)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:168:27)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at ParsePromise.<anonymous> (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:163:29)
    at ParsePromise.wrappedResolvedCallback (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:158:41)
    at ParsePromise.executor.value (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/ParsePromise.js:89:36)
    at [object Object].xhr.onreadystatechange (/Users/alex/dev/parse/parse-server/node_modules/parse/lib/node/RESTController.js:115:21)
    at [object Object].dispatchEvent (/Users/alex/dev/parse/parse-server/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
npm ERR! Test failed.  See above for more details.
```

**Comment by flovilmart** [comment]
We're undergoing a major refactor of the push architecture with #3080. 

Closing for now, as the refactor will completely break with that PR.

**Pull request closed without merging**
