### PR TITLE
DBController refactoring

### PR DESCRIPTION
**Pull request by flovilmart**
Removes adaptiveCollection from DatabaseController
    
- All collections manipulations are now handled by a DBController
- Adds .Unsafe on DBController that generates a DBController that skips className validations and key names validations (this allows using the DBController for internal classes like _PushStatus and 'private' properties like _perishable_token)
- Adds ability to configure RestWrite with multiple writes
- Moves some transfirmations to MongoTransform as they output specific code

### CODE REVIEW

**Comment by drew-gross** [comment]
> Adds optional flags to configure an unsafe databaseController for direct
  access


I don't think we want this. Obviously we wouldn't be able to use it internally, or the entire concept of database adapters won't work. If someone wants direct DB access in their cloud code, they can just use the driver like they would if they weren't writing a Parse app.

**Comment by flovilmart** [comment]
This is not to provide direct DB access, bust skip className and key validation so we can use The DB controller instead of the adaptive collection. Problem with adaptive collection is that it's highly opinionated towards the driver.

**Comment by drew-gross** [comment]
Rather than allowing the "unsafe" version  to do anything at all, can we just allow it to write classes and fields that start with an underscore? Also I think @nlutsenko's strategy with the adaptive collection was to first make it less tightly coupled, and then make it less opinionated in a separate phase.

**Comment by flovilmart** [comment]
That's the goal of the unsafe. Not sure we're not saying the same thing differently.

The problem with the adaptiveCollection abstraction, is that it would force to move all transformations inside the collection instead of outside, in DBController

---> REST format ---> DBController -- adapter.transform -> adaptiveCollection 

With this architecture the adapter is fully and solely responsible to transform, untransform, store and retrieve data. The DBController orchestrates all operations, and takes REST format and returns REST format. The rest of the module only talks in REST to the DBAdapater, abstracting to the right level.

For a SQL DB, as the transform would spit out strings that would be passed as is to the adapativeCollection. AdaptiveCollectoon means that it's an adapter specific collection, not a collection that takes a standard query format.

**Comment by nlutsenko** [comment]
Sorry, sir, looks like this needs rebase. :) Pass back hen you are done.

**Comment by flovilmart** [comment]
@nlutsenko it's all yours!

**Comment by flovilmart** [comment]
@drew-gross , @nlutsenko what should we do with that PR? That makes the internals use the proper Rest format, I'm open to refactor differently/further if needed.

**Comment by drew-gross** [comment]
I had been planning to let @nlutsenko continue with reviewing since he has done more of the db adapter code, and has more context on how it should work.

**Comment by nlutsenko** [comment]
I'll take a look at it after F8 (which is tomorrow and Wednesday).
Sorry it takes that much time to get to it, am tangled in other things...

**Comment by flovilmart** [comment]
Good luck for F8! Let me know when you get some time on slack, if it needs a rebase at that time I'll do a quick one.

**Comment by drew-gross** [comment]
I think @nlutsenko is busy and this looks pretty solid to me and passes tests. The DB Adapter API will need a lot of changes anyway so I say might as well merge.

**Comment by flovilmart** [comment]
Alright then!

**Pull request merged**
