### PR TITLE
Makes sudo: false

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by acinader** [comment]
no joy

**Comment by flovilmart** [comment]
Nope.... not sure what's going on...

**Comment by acinader** [comment]
looks like we're erroring on not having postgis 2.3.  travis docs say travis has 2.1.

**Comment by flovilmart** [comment]
Yeah, I reverted to precise instead of trusty and it seems to be ok

**Comment by flovilmart** [comment]
Not sure how to force posgis version as their thing is borked

**Comment by acinader** [comment]
looks good.

**Comment by flovilmart** [comment]
Yay!

**Pull request merged**
