### PR TITLE
SNS Prep work

### PR DESCRIPTION
**Pull request by rogerhu**
Need to reuse APNS and GCM code.

@gfosco @flovilmart

### CODE REVIEW

**Comment by flovilmart** [comment]
please rebase on master

**Comment by rogerhu** [comment]
I've prepped https://github.com/rogerhu/parse-server-sns-adapter

1) My issue of course is being able to run tests without the use of submodule.
2) The 2nd commit (https://github.com/ParsePlatform/parse-server/pull/1158/commits/04e2c4848d6194586e21111293461cf528dcaf76) is intended to allow importing these things directly.  I would need to change the import paths (https://github.com/rogerhu/parse-server-sns-adapter/blob/master/src/SNSPushAdapter.js#L5-L14) to match though.  

What is the best way to allow tests to run while also being able to publish?

**Comment by flovilmart** [comment]
We're in the process of removing all adapters from parse-server, not sure if you shouldn't instead focus on a standalone package.

**Comment by flovilmart** [comment]
I'll probably move the ParsePushAdapter to parse-server-push-adapter with all the needed dependencies. Stay tuned !

**Comment by rogerhu** [comment]
Closing in lieu of https://github.com/parse-server-modules/parse-server-sns-adapter work.

**Pull request closed without merging**
