### PR TITLE
Reverts calling next() after handling response

### PR DESCRIPTION
**Pull request by flovilmart**
Reverts ParsePlatform/parse-server#2559

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2634/files/41853a0fa6b5f729f0890e98d4dba7f46ca48064..82f947a2ef4551f9c816f651825041c09bf4c374)

**Comment by facebook-github-bot-9** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2634/files/82f947a2ef4551f9c816f651825041c09bf4c374..bd3b512cbbff994d125cef3d23b13af7e910731f)

**Comment by flovilmart** [comment]
Closes #2362, #2580, and probably other issues... 

Happy to discuss here. @blacha if you're ok with it, we'll move forward removing that next() call, even I don't like not having it, but if it's painful for everyone, let's stop the pain.

**Comment by drew-gross** [comment]
Could we get a regression test on this? Seem like is issue is a tricky one.

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2634/files/6c4e7da069dc40cbbaf55a08f7fff4cc60ffc79b..924686b94503b1e072ceb6ae29f02cf11739e60b)

**Comment by facebook-github-bot-3** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2634/files/924686b94503b1e072ceb6ae29f02cf11739e60b..a482019f19b3ce366abe4089a6e02e23da8131ad)

**Pull request merged**
