### PR TITLE
Features Endpoint for Dashboard.

### PR DESCRIPTION
**Pull request by peterdotjs**
Features endpoint based on discussion #611

### CODE REVIEW

**Comment by drew-gross** [comment]
Sweet! I think @nlutsenko made a middleware for enforcing master key on an endpoint, but otherwise LGTM.

**Comment by nlutsenko** [comment]
Yup, lgtm otherwise, encourage to use the middleware if you need to enforce the master key.

**Comment by peterdotjs** [comment]
@nlutsenko can you confirm you're referring to the middleware being used in [`FilesRouter`](https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FilesRouter.js#L29)? I'm not seeing it used in any of the `PromiseRouter` files.

**Comment by nlutsenko** [comment]
@peterdotjs Yes, there was functionality added by @flovilmart that allowed plugging middleware into PromiseRouter.

**Comment by drew-gross** [comment]
I think we can probably skip the single element array. Also, I remembered the that endpoint for getting a single schema doesn't use `results` :( so maybe it's not critical

**Comment by flovilmart** [comment]
@peterdotjs the problem with the middleware thing is that it doesn't exit early... for some obscure reason returning a Promise.reject() keeps it going

**Comment by drew-gross** [comment]
Oh yeah, were you going to include the server version in this endpoint? I wanted to display it in the apps index. Also it would be pretty sweet to have the server "version" be a git hash or something if you are hacking on the server.

Fake edit: The output of `git describe --dirty` sounds ideal for the "version" while you are developing.

**Comment by drew-gross** [comment]
Sorry for all the scope creep :( feel free to ignore

**Comment by drew-gross** [comment]
Note: Logs endpoint is different from the Parse.com logs endpoint, so it should be marked as not supported until we can get feature parity (enough for the dashboard to work, at least

**Comment by flovilmart** [comment]
@drew-gross could we get a spec for the logs endpoint?

**Comment by drew-gross** [comment]
Easiest way is probably to go to dashboard.parse.com and view the two logs pages and capture the request.

**Comment by drew-gross** [comment]
Config endpoint also doesn't match close enough to use on the dashboard.

**Comment by flovilmart** [comment]
I can work on that

**Comment by drew-gross** [comment]
Merging this myself so I can do some work on top of it.

**Pull request merged**
