### PR TITLE
#506 fix: Deleting a file does not delete from fs.files

### PR DESCRIPTION
**Pull request by maninga**
As illustrated in https://mongodb.github.io/node-mongodb-native/api-generated/gridstore.html#unlink
the Gridstore should be instanciated on readOnly mode, then unlink removes from fs.chunks and fs.files

### CODE REVIEW

**Comment by flovilmart** [comment]
@maninga can you add a test in order to test that it's working correctly?

**Comment by facebook-github-bot-7** [comment]
@maninga updated the pull request.

**Comment by maninga** [comment]
ok, I just push that so the pull request is updated.

**Comment by facebook-github-bot-3** [comment]
@maninga updated the pull request.

**Pull request merged**
