### PR TITLE
Better support for arrays of objects in Postgres

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by flovilmart** [comment]
@kulshekhar can you check that one? It fixes a crash on the travis-ci, the tests are likely to fail locally too IMHO.

**Comment by kulshekhar** [comment]
Sure. I'm taking a look at this now

**Comment by kulshekhar** [comment]
@flovilmart something else is causing the current tests to fail. When I rebased this branch with master and tested again, it didn't change anything (the tests failed with the same errors as before)

**Comment by flovilmart** [comment]
Yeah after the rebase on master, tests are failing. master is currently broken for pg tests.

**Comment by kulshekhar** [comment]
I have a fix for one of the failures but it seems like a hack. Should I submit a PR with that so that I can seek feedback on the best way forward?

**Comment by flovilmart** [comment]
go ahead!

**Comment by flovilmart** [comment]
To me it seems that it's deadlocking with batch calls or something...

**Comment by kulshekhar** [comment]
> To me it seems that it's deadlocking with batch calls or something...

That particular error is being caused due to a test in `ParseAPI.spec.js`. It is attempting to create a class when the schema hasn't been created yet. Addressed in the first part of #2956

**Comment by flovilmart** [comment]
@kulshekhar by disabling the creation transaction: https://travis-ci.org/ParsePlatform/parse-server/builds/171484959
#2957

**Comment by kulshekhar** [comment]
Yeah. I've been following these builds right now :)

That was how it was originally, right (the createClass method)?

**Comment by flovilmart** [comment]
I believe yeah

**Comment by kulshekhar** [comment]
But that'll cause a race (I ended up wasting a lot of time trying to find the source!)

If I can make one suggestion - can you try restoring the transaction and preceding it with `return this._ensureSchemaCollectionExists()` as in #2956 ?

**Comment by flovilmart** [comment]
It's called here: https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L466

**Comment by kulshekhar** [comment]
yeah. 

Looks like your last PR has passed all tests. :champagne: 

Maybe I should fetch the latest version as first see if the race still exists :)

**Comment by flovilmart** [comment]
@kulshekhar you can probably try to get the transaction working correctly at a later time, now that all test pass, that would be easy.

**Pull request closed without merging**
