### PR TITLE
Disable tests that don't work in Postgres, and don't start a mongo for postgres tests

### PR DESCRIPTION
**Pull request by drew-gross**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
@drew-gross updated the pull request.

**Comment by drew-gross** [comment]
Opted to make the PR into master. Hopefully postgres tests don't continue to be a pain, it would be nice to prevent postgres regressions in master if possible.

**Comment by drew-gross** [comment]
@flovilmart

**Comment by flovilmart** [comment]
Let's see how it goes, once Travis finishes.

**Comment by drew-gross** [comment]
Looks like both postgreses are passing. Just waiting on mongo now. Being able to not start mongo when running postgres tests should help somewhat.

**Comment by flovilmart** [comment]
looks good! Merging!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.13](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
