### PR TITLE
Clear sessions

### PR DESCRIPTION
**Pull request by flessard**
fix bug when you try to change user password whit user.save(null, {
useMasterKey: true }) cause Object not found error.

### CODE REVIEW

**Comment by flovilmart** [comment]
@flessard can you add Unit tests that will make sure we don't introduce regressions there at a later point?

**Comment by flessard** [comment]
By trying to create a unit test i found the function Parse.User.become(sessionToken) always return object not found even if you pass a valid sessionToken.

If you change this unit test «changing password clears sessions» by removing this line «newUser.set('password', 'facebook');», this test should be fail but this is not.

**Comment by flovilmart** [comment]
> By trying to create a unit test i found the function Parse.User.become(sessionToken) always return object not found even if you pass a valid sessionToken.

That means the sessionToken is invalid right?

>If you change this unit test «changing password clears sessions» by removing this line «newUser.set('password', 'facebook');», this test should be fail but this is not.

So the test should be:

1. create a new user (username, password) // Should succeed
1. capture the current sessionToken in a variable for later use
1. Become the use with the sessionToken -> // should succeed
1. Change the password // should succeed
1. The session token should be updated in the result as the password has changed // newSessionToken != currentSession token
1. become(oldSessionToken) // should fail

**Comment by flessard** [comment]
Yes, `Parse.User.become` has a bug.
If you don't change the password of user, parse-server will not clear the curent session. 
I just create a unit test  for this bug, and this test fail. juste try it.

  ```
 it('test parse user become', (done) => {
    var sessionToken = null;
    Parse.Promise.as().then(function() {
      return Parse.User.signUp("flessard", "folo",{'foo':1});
    }).then(function(newUser) {
      equal(Parse.User.current(), newUser);
      sessionToken = newUser.getSessionToken();
      ok(sessionToken);
      newUser.set('foo',2);
      return newUser.save();
    }).then(function() {
      return Parse.User.become(sessionToken);
    }).then(function(newUser) {
      equal(newUser.get('foo'), 2);
      done();
    }, function(e) {
      fail('The session should still be valid');
      done();
    });
  });
```

**Comment by flovilmart** [comment]
@flessard:

in src/Router/Routers:

```   
handleGet(req) {
    // Add that:
    // to handle me call when calling User.become
    if (req.params.objectId === "me" && req.auth.user) {
      req.params.objectId = req.auth.user.id;
    }
    req.params.className = '_User';
    return super.handleGet(req);
}
```

**Comment by flovilmart** [comment]
@flessard actually, that should return {"code":209,"error":"invalid session token"}

**Comment by flessard** [comment]
If i try your fix, this unit-test `changing password clears sessions` fail. I try to figure why this fail.

**Comment by flovilmart** [comment]
@flessard there is a problem with the order of the query processing, the /user/me should be before /users/:objectId otherwise the route may not be taken properly. Check out that branch there: https://github.com/flovilmart/parse-server/tree/clear-sessions

**Comment by flovilmart** [comment]
you can pull from mine or we replace the PR with the updated one.

**Comment by flovilmart** [comment]
@flessard I've pushed another PR with the same changes as you and more tests.

**Comment by flessard** [comment]
@flovilmart Nice thanks.

**Comment by flovilmart** [comment]
you can close this one :)

**Pull request closed without merging**
