### PR TITLE
Fix flaky test

### PR DESCRIPTION
**Pull request by drew-gross**
this seems to have helped with the flaky test, by using `getOneSchema` to get the schema, instead of `this.data` which can get unloaded randomly.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Pull request merged**
