### PR TITLE
Converts httpRequest body to string if needed

### PR DESCRIPTION
**Pull request by natanrolnik**

### CODE REVIEW

**Comment by natanrolnik** [comment]
As discussed in #88

**Comment by gfosco** [comment]
I saw and merged #105 before this... Both claiming to fix the same issue... Are they both valuable together, or which one is better?

**Comment by natanrolnik** [comment]
From what my JS knowledge allowed, I understand that they are different things. They are similar names but in different locations. Maybe the title of my commit/PR should be changed.

- Mine takes care of converting the body to string in case it's an object; and we are talking about the httpRequest defined in `Parse.Cloud.httpRequest`.
- #105 takes care of the conversion in the `where` of a find in the `handleFind` function.

**Comment by r4zzz4k** [comment]
I agree, they seem totally unrelated. https://github.com/ParsePlatform/parse-server/pull/105 is about querying objects within current Parse App, and this one is associated with general-purpose HTTP queries from within Cloud Code.

**Comment by gfosco** [comment]
:+1:

**Pull request merged**
