### PR TITLE
Mask sensitive information when logging

### PR DESCRIPTION
**Pull request by Marco129**
Related to issue #1704
Not sure whether the test case should put inside `FileLoggerAdapter.spec.js`

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
@Marco129 updated the pull request.

**Comment by drew-gross** [comment]
I think it might make more sense to do this at the object level, ie. check if the request is for the _User class, and set the password to `********` if it is. Then we will only filter exactly what we want, instead of catching things like `password: blah` inside other columns or inside objects. That might require bigger changes to where we log stuff though. Thoughts?

**Comment by facebook-github-bot-5** [comment]
@Marco129 updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@Marco129 updated the pull request.

**Comment by Marco129** [comment]
@drew-gross Agree with that. Updated the PR to reflect the changes.

**Comment by jameslin101** [comment]
I'm still getting passwords being shown in my log file here

`at=info`` method=GET path="/1/login?password=somepassword&username=someusername" host=someapp.herokuapp.com request_id=a8dae8fc-7c0a-4e2c-82de-493b168e2291 fwd="54.227.100.56" dyno=web.1 connect=0ms service=382ms status=200 bytes=1632

**Pull request merged**
