### PR TITLE
Removed extra /logout handler

### PR DESCRIPTION
**Pull request by gfosco**

### CODE REVIEW

**Comment by drew-gross** [comment]
Why delete this one? The other one does less error handling.

**Comment by gfosco** [comment]
Logout shouldn't fail.  This one silently succeeds always and I believe that to be the correct approach.

**Comment by drew-gross** [comment]
No the other one doesn't silently succeed if, for example, the database can't be reached.

**Comment by drew-gross** [comment]
Cool. I would like to see some tests for this one as it's a security issue. (imagine a user logs thinks they have logged out from a public computer, but really the next person to use the computer can still log in as them)

Hopefully we can avoid having to make any CVEs for quite awhile :)

**Comment by drew-gross** [comment]
Yay passing tests!

**Comment by woodardj** [comment]
We're observing this code now always deleting the most recently created _Session. How do we call Parse.User.logout() and specify which session we want to delete?

**Comment by adambarghouthi** [comment]
@woodardj were you able to figure it out? I'm having the same problem

**Pull request merged**
