### PR TITLE
Obfuscate password name value pairs in log strings

### PR DESCRIPTION
**Pull request by flovilmart**
fixes: #2680

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2755/files/35b1549efcf998e74e465a7cfa303544cfb15571..d1065888dc0bf1e7137b4c99b7d704157411da20)

**Comment by acinader** [comment]
@flovilmart oh, now i see what you mean in https://github.com/ParsePlatform/parse-server/issues/2680#issuecomment-248466526

I think that what you're suggesting is trying something like:

```
export class LoggerController extends AdaptableController {

  log(level, args) {
    args = [].concat(level, [...args]);
+   args.forEach(e => e.cleanLogString(e))
    this.adapter.log.apply(this.adapter, args);
  }
```

and remove cleaning from the clients responsibility.  I like it and will take a look, but can't get to tonight...will need to take a look at what comes into ...args :)

**Comment by flovilmart** [comment]
No problem, there's no rush :)

**Comment by skinp** [comment]
LGTM

**Comment by flovilmart** [comment]
Alright let's merge that so it's available on the latest branch, we'll refactor later

**Pull request merged**
