### PR TITLE
Adds eslint and npm run lint

### PR DESCRIPTION
**Pull request by flovilmart**
✖ 703 problems (703 errors, 0 warnings)

### CODE REVIEW

**Comment by drew-gross** [comment]
I vote for http://standardjs.com/ instead.

**Comment by drew-gross** [comment]
I also vote that this be enforced in a status check. Having it be enforced by humans sounds like a lot of work for very little gain.

**Comment by flovilmart** [comment]
We'll add it before the tests. Didn't knew about standard, is it as flexible as eslint with different rules for different folders, globals etc...

**Comment by nlutsenko** [comment]
StandardJS + not touching existing code to maintain blame and context + status check on diffs. +1

**Comment by steven-supersolid** [comment]
StandardJS is a cool idea but uses the no semicolon rule. Will look a bit different without them but I guess OK if they are not required. I couldn't see anything about support for globals but only took a quick look

**Comment by flovilmart** [comment]
Now it's fully linted with eslint, standard rules + keyword spacing and allow console, we could move to standardjs, not sure it's as well integrated in IDE's not for the global var supports.

**Comment by flovilmart** [comment]
@nlutsenko seems complicated not to touch existing code with 703 errors...

**Comment by flovilmart** [comment]
And standard enforces no semi-colon which yields 2500 changes

**Pull request closed without merging**
