### PR TITLE
add multi path for cloud code

### PR DESCRIPTION
**Pull request by panjiubang**
add cloud code file support multi path, 
different business use different cloud code file

### CODE REVIEW

**Comment by flovilmart** [comment]
Hi, thanks for the Pr, what would be your use case for that? Any reason you don't require the necessary modules from the main one?

**Comment by panjiubang** [comment]
1.  my purpose  is agreement a rule in the team, and define cloud code in one dir(such as cloud dir),I will scanner the dir when init parse-server,so developers only need to put their own cloud file in the dir without to do anything else(such as module require)
2.  the second reason：add this feature will not affect the original function

**Comment by flovilmart** [comment]
Yeah, but I believe it's misleading and can be problematic. You can do that externally in your cloud code main.

**Comment by panjiubang** [comment]
ok
another question: how to use cloud code when a function type

**Comment by flovilmart** [comment]
```
new ParseServer({
  cloud: function() {
      // do something
  }
});
```

**Comment by panjiubang** [comment]
ok, but I didn't known the use case,  can you take an example    //do something

**Comment by panjiubang** [comment]
follow you advice , I realized in mian.js like this:

var fs = require('fs');
fs.readdir("./cloud",function(err,files)
{
  for (var index in files)
  {
      if (!files[index].startsWith("."))
      {
        require("./" + files[index]);
      }
  }
});

any problem?

**Comment by flovilmart** [comment]
You should probably ask on stackoverflow those questions.

**Comment by panjiubang** [comment]
ok, thank you

**Pull request closed without merging**
