### PR TITLE
Adds support for --verbose and verbose option when running ParseServer

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by flovilmart** [comment]
I don't do any check on the validity of the specified log level.
By default setting --verbose or verbose =  true, sets the logLevel to silly (we don't use anything above verbose for now)

**Comment by drew-gross** [comment]
Can you split this into 2 PRs? I think the logging stuff makes sense, but the settings endpoint is a new API that probably deserves more discussion.

**Comment by flovilmart** [comment]
yep

**Comment by flovilmart** [comment]
waiting for travis then merging

**Pull request merged**
