### PR TITLE
Generate tokens with CSPRNG

### PR DESCRIPTION
**Pull request by dchest**
Package hat, used to generate session and some other tokens uses
non-cryptographic random number generator. Replace it with the
cryptographically secure one. The result has the same format
(32-character hex string, 128 bits of entropy).

### CODE REVIEW

**Comment by dchest** [comment]
Ideally, I'd create a function:

```
function randomToken() {
   return crypto.randomBytes(16).toString('hex');
}
```

and use it everywhere (removing hat dependency), but don't know where to put it. Should we have `utils.js`? Please let me know how to proceed and I'll modify this PR.

**Comment by nlutsenko** [comment]
This is a nice idea, security few!

Agreed with a custom function for these things. `util.js` sounds good, though maybe `cryptoUtils.js`, since the former has a tendency to grow with a bunch of random unrelated things.
One more thing: we probably can remove `hat` at all from package.json, since we won't need it anymore.

Feel free to update this PR and we'll happily merge this in, unless @drew-gross has any objections.

**Comment by dchest** [comment]
All right, I've introduced `cryptoUtils.js` and moved all related random string generation there, removing 2 dependencies (`hat` and `randomstring`). I've also created some tests. (I haven't yet test this stuff locally, as I haven't set up environment on this computer yet.)

**Comment by dchest** [comment]
I'll rebase it in a few hours.

**Comment by nlutsenko** [comment]
Great, looks good so far. Can we use ES6 import/export style by any chance?

**Comment by nlutsenko** [comment]
Passing back purely for rebase.

**Comment by dchest** [comment]
Whee! Sorry for the noise, it's ready for review now. With regards to modules, I chose to use whatever import style the file uses: when it's CommonJS-style, I used CommonJS, when it already had ES6 imports, I used ES6 import. The .spec.js files are not transpiled, so I used `require` there.

**Comment by gfosco** [comment]
Can you rebase this?  Thank you.

**Pull request merged**
