### PR TITLE
Push: this function was extremely slow.

### PR DESCRIPTION
**Pull request by jeacott1**
this fix reduces the time to process push to 165k installations
from 282738.599ms (almost 5 minutes of total server lockup!)
to just 16.283ms!

### CODE REVIEW

**Comment by flovilmart** [comment]
16ms really? That seems wrong.

**Comment by jeacott1** [comment]
I timed it. Try it yourself and see!  Only timing this function,  nothing else.

**Comment by flovilmart** [comment]
I trust you on it being faster :) batching will come soon enough, there's a PR open for that, that will also enable queuing in the adapter and distrubute the workload at large

**Comment by kontextbewusst** [comment]
I can confirm that this greatly reduces the server load. Pushing to 30k devices previously turned our server unresponsive for several minutes.

**Comment by ortimanu** [comment]
@jeacott1 can you briefly explain how that changed caused such a big variation in performance? I am currently using a previous parse server version and my server is getting unresponsive for several minutes. I am thinking of updating to this version, but I am not sure to do it because of #3562 introduced here. What do you guys recommend me to do? 

PD: Do you know why the server becomes unresponsive when sending the pushes without this update? I cannot find why.

**Pull request merged**
