### PR TITLE
Continue with postgres support

### PR DESCRIPTION
**Pull request by drew-gross**
Also move some mongo specific logic out of mongo adapter (createdAt/updatedAt/password stuff) and some non-mongo-specific stuff (query validation) out of mongo adapter.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
@drew-gross updated the pull request.

**Comment by devmsh** [comment]
Can we test it? or it's still WIP?

**Comment by drew-gross** [comment]
Still work in progress. The tests don't even run to completion successfully.

**Comment by facebook-github-bot-6** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@drew-gross updated the pull request.

**Pull request merged**
