### PR TITLE
Add fast-test script to package.json that doesn't run code-coverage.

### PR DESCRIPTION
**Pull request by nlutsenko**
Waaaaay faster local development.
@drew-gross @andrewimm - how can I make it work with `posttest` and have an ability to pass arguments into it?

### CODE REVIEW

**Comment by flovilmart** [comment]
Did you try: 

; npm run posttest -- $?

**Comment by flovilmart** [comment]
You need -- between the npm run (cmd) -- args to pass arguments.

**Comment by nlutsenko** [comment]
That's  great, how do I reference them inside the script?
As you can see - k have pretest and post test inside of the same script, as those won't get picked up.

**Comment by flovilmart** [comment]
would be better to run coverage only on TRAVIS=1 OR COVERAGE=1 what do you think?

**Comment by nlutsenko** [comment]
Continuing in #807

**Pull request closed without merging**
